// Re-exported so downstream crates can use the exact same `sqlx` version these trait
// signatures are built against. Depending on `sql_traits::sqlx` instead of a separately
// declared `sqlx` guarantees a single compiled copy, avoiding "expected `Pool`, found
// `Pool`" errors from two incompatible sqlx versions. `async_trait` is re-exported for
// convenience, since implementing these traits requires the `#[async_trait]` attribute.
pub use ::async_trait;
pub use ::sqlx;

use ::async_trait::async_trait;
use ::sqlx::PgPool;

/// Indicates that a type has a primary key, exposing it as an associated type.
pub trait HasPrimaryKey {
    type PrimaryKey: Send;
}

/// Fetches the most recent record of this type from the database.
#[async_trait]
pub trait GetLatestRecord: Sized {
    async fn get_latest_record(pool: &PgPool) -> Result<Option<Self>, sqlx::Error>;
}

/// Fetches the record of this type from the database with the given primary key value.
///
/// `HasPrimaryKey::PrimaryKey` is already declared `Send`, so no extra bound is needed here.
#[async_trait]
pub trait GetRecord: Sized + HasPrimaryKey {
    async fn get_record(
        pool: &PgPool,
        primary_key: <Self as HasPrimaryKey>::PrimaryKey,
    ) -> Result<Option<Self>, sqlx::Error>;
}

/// Fetches a single record of this type from the database matching the given filter.
#[async_trait]
pub trait GetRecordWhere<T>: Sized
where
    T: Send,
{
    async fn get_record_where(pool: &PgPool, where_params: T) -> Result<Option<Self>, sqlx::Error>;
}

/// Retrieves all records of this type from the database.
#[async_trait]
pub trait ListRecords: Sized {
    async fn get_all(pool: &PgPool) -> Result<Vec<Self>, sqlx::Error>;
}

/// Retrieves all records of this type from the database matching the given filter.
#[async_trait]
pub trait ListRecordsWhere<T>: Sized {
    async fn get_records(pool: &PgPool, where_params: T) -> Result<Vec<Self>, sqlx::Error>;
}

/// Inserts a single record into the database.
#[async_trait]
pub trait InsertSQL {
    /// The type returned after insertion.
    ///
    /// This is typically different from the input type because fields like
    /// the primary key are generated by the database and not provided in
    /// the creation request.
    type ReturnType: Sized;
    async fn insert_sql(self, pool: &PgPool) -> Result<Self::ReturnType, sqlx::Error>;
}

/// Inserts multiple records into the database in a single operation.
#[async_trait]
pub trait BulkInsertSQL: Sized + Sync {
    /// The type returned after insertion.
    ///
    /// This is typically different from the input type because fields like
    /// the primary key are generated by the database and not provided in
    /// the creation request. For bulk operations where returning all created
    /// records may be expensive, this can also be set to `()`.
    type ReturnType: Sized;
    async fn bulk_insert_sql(
        pool: &PgPool,
        records: &[Self],
    ) -> Result<Self::ReturnType, sqlx::Error>;
}

/// Deletes a record from the database by its primary key.
#[async_trait]
pub trait DeleteSQL: HasPrimaryKey
where
    <Self as HasPrimaryKey>::PrimaryKey: Send,
{
    type ReturnType: Sized;
    async fn delete_sql(
        pool: &PgPool,
        primary_key: <Self as HasPrimaryKey>::PrimaryKey,
    ) -> Result<Self::ReturnType, sqlx::Error>;
}

/// Deletes all records of this type from the database matching the given filter.
#[async_trait]
pub trait DeleteRecordsWhere<T>
where
    T: Send,
{
    type ReturnType: Sized;
    async fn delete_records_where(
        pool: &PgPool,
        where_params: T,
    ) -> Result<Self::ReturnType, sqlx::Error>;
}
